// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repasoFinal2daMesa.data;

#nullable disable

namespace repasoFinal2daMesa.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20241127131256_population")]
    partial class population
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("repasoFinal2daMesa.Models.Configuraciones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("configuraciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440006"),
                            Nombre = "padding-top",
                            Valor = "50px"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440007"),
                            Nombre = "padding-left",
                            Valor = "100px"
                        });
                });

            modelBuilder.Entity("repasoFinal2daMesa.Models.Provincias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("provincias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            Nombre = "Salta"
                        });
                });

            modelBuilder.Entity("repasoFinal2daMesa.Models.Sucursales", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCiudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdProvincia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("IdTipo");

                    b.ToTable("sucursales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c64c4900-901b-4241-99b4-ae2274235f7b"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 761, DateTimeKind.Local).AddTicks(6570),
                            IdCiudad = "CBA001",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            Nombre = "Sucursal Córdoba Centro",
                            NombreTitular = "María",
                            Telefono = "0351-4567890"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440009"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 764, DateTimeKind.Local).AddTicks(7864),
                            IdCiudad = "CBA5551",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Sucursal Córdoba norte",
                            NombreTitular = "Joaquin",
                            Telefono = "0351-45678888"
                        },
                        new
                        {
                            Id = new Guid("4b9530b2-30e3-4acf-91b8-5ec2efcc24fd"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 764, DateTimeKind.Local).AddTicks(7901),
                            IdCiudad = "CB661",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Sucursal Córdoba sur",
                            NombreTitular = "Joaquin",
                            Telefono = "0351-45678888"
                        },
                        new
                        {
                            Id = new Guid("5c9a4b0f-6554-40ff-a906-35b54a1daedc"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 764, DateTimeKind.Local).AddTicks(7907),
                            IdCiudad = "CB221",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Sucursal Córdoba Oeste",
                            NombreTitular = "Joaquin",
                            Telefono = "0351-45678888"
                        },
                        new
                        {
                            Id = new Guid("0a900986-a6b9-4622-bbb2-b46078b01baf"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 764, DateTimeKind.Local).AddTicks(7911),
                            IdCiudad = "BA001",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Sucursal Córdoba Oeste",
                            NombreTitular = "Joaquin",
                            Telefono = "11-45678228"
                        },
                        new
                        {
                            Id = new Guid("f9ce11fd-e42f-4bb1-a1bb-6921e0349950"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 764, DateTimeKind.Local).AddTicks(7916),
                            IdCiudad = "SA777",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Sucursal salta Oeste",
                            NombreTitular = "Joaquin",
                            Telefono = "88-4567887448"
                        },
                        new
                        {
                            Id = new Guid("43588888-df4b-4a51-9dc7-4b81aa0cc6c6"),
                            ApellidoTitular = "Gómez",
                            FechaAlta = new DateTime(2024, 11, 27, 10, 12, 55, 764, DateTimeKind.Local).AddTicks(7920),
                            IdCiudad = "SA1",
                            IdProvincia = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            IdTipo = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Sucursal salta Oeste",
                            NombreTitular = "Joaquin",
                            Telefono = "88-45673388"
                        });
                });

            modelBuilder.Entity("repasoFinal2daMesa.Models.Tipos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tipos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            Nombre = "Pequeña"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Nombre = "Grande"
                        });
                });

            modelBuilder.Entity("repasoFinal2daMesa.Models.Sucursales", b =>
                {
                    b.HasOne("repasoFinal2daMesa.Models.Provincias", "Provincias")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("repasoFinal2daMesa.Models.Tipos", "Tipos")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincias");

                    b.Navigation("Tipos");
                });
#pragma warning restore 612, 618
        }
    }
}
